version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j-niklas-playground
    environment:
      NEO4J_AUTH: neo4j/12345678
      NEO4J_PLUGINS: '["graph-data-science", "apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: "gds.*,apoc.*,gds.util.*,n10s.*"
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_dbms_unmanaged__extension__classes: "n10s.endpoint=/rdf"
      NEO4J_dbms_security_procedures_allowlist: "n10s.*"
    volumes:
      - ./data:/data                # For persistence of data
      - ./import:/import            # Import directory for data files
      - ./plugins:/plugins          # Plugin directory
    ports:
      - "7474:7474"                 # HTTP
      - "7687:7687"                 # Bolt
    restart: unless-stopped
